export const deliveryZones = [
  {
    id: 'cairo',
    name_en: 'Cairo',
    name_ar: 'القاهرة',
    defaultZone: 'Zone 1',
    cities: [
      { name_en: 'Cairo City', name_ar: 'مدينة القاهرة', zone: 'Zone 1' },
      { name_en: 'El Obour', name_ar: 'العبور', zone: 'Zone 2' },
      { name_en: 'Badr city', name_ar: 'مدينة بدر', zone: 'Zone 2' },
      { name_en: 'El Marg', name_ar: 'المرج', zone: 'Zone 2' },
      { name_en: 'El Sherouk', name_ar: 'الشروق', zone: 'Zone 2' },
      { name_en: '10th of Ramadan City', name_ar: 'مدينة العاشر من رمضان', zone: 'Zone 2' },
    ],
  },
  {
    id: 'giza',
    name_en: 'Giza',
    name_ar: 'الجيزة',
    defaultZone: 'Zone 1',
    cities: [],
  },
  {
    id: 'alexandria',
    name_en: 'Alexandria',
    name_ar: 'الإسكندرية',
    defaultZone: 'Zone 2',
    cities: [],
  },
  {
    id: 'beheira',
    name_en: 'Beheira',
    name_ar: 'البحيرة',
    defaultZone: 'Zone 2',
    cities: [],
  },
  {
    id: 'sharkia',
    name_en: 'Sharkia',
    name_ar: 'الشرقية',
    defaultZone: 'Zone 3',
    cities: [
      { name_en: 'Zagazig', name_ar: 'الزقازيق', zone: 'Zone 3' },
      { name_en: '10th of Ramadan', name_ar: 'العاشر من رمضان', zone: 'Zone 2' },
      { name_en: 'Belbeis', name_ar: 'بلبيس', zone: 'Zone 3' },
      { name_en: 'Abu Hammad', name_ar: 'أبو حماد', zone: 'Zone 3' },
    ],
  },
  {
    id: 'gharbia',
    name_en: 'Gharbia',
    name_ar: 'الغربية',
    defaultZone: 'Zone 3',
    cities: [],
  },
  {
    id: 'dakahlia',
    name_en: 'Dakahlia',
    name_ar: 'الدقهلية',
    defaultZone: 'Zone 3',
    cities: [],
  },
  {
    id: 'portsaid',
    name_en: 'Port Said',
    name_ar: 'بورسعيد',
    defaultZone: 'Zone 3',
    cities: [],
  },
  {
    id: 'ismailia',
    name_en: 'Ismailia',
    name_ar: 'الإسماعيلية',
    defaultZone: 'Zone 3',
    cities: [],
  },
  {
    id: 'suez',
    name_en: 'Suez',
    name_ar: 'السويس',
    defaultZone: 'Zone 3',
    cities: [],
  },
  {
    id: 'faiyum',
    name_en: 'Faiyum',
    name_ar: 'الفيوم',
    defaultZone: 'Zone 4',
    cities: [],
  },
  {
    id: 'benisuef',
    name_en: 'Beni Suef',
    name_ar: 'بني سويف',
    defaultZone: 'Zone 4',
    cities: [],
  },
  {
    id: 'minya',
    name_en: 'Minya',
    name_ar: 'المنيا',
    defaultZone: 'Zone 4',
    cities: [],
  },
  {
    id: 'asyut',
    name_en: 'Asyut',
    name_ar: 'أسيوط',
    defaultZone: 'Zone 4',
    cities: [],
  },
  {
    id: 'sohag',
    name_en: 'Sohag',
    name_ar: 'سوهاج',
    defaultZone: 'Zone 4',
    cities: [],
  },
  {
    id: 'qena',
    name_en: 'Qena',
    name_ar: 'قنا',
    defaultZone: 'Zone 5',
    cities: [],
  },
  {
    id: 'luxor',
    name_en: 'Luxor',
    name_ar: 'الأقصر',
    defaultZone: 'Zone 5',
    cities: [],
  },
  {
    id: 'aswan',
    name_en: 'Aswan',
    name_ar: 'أسوان',
    defaultZone: 'Zone 5',
    cities: [],
  },
  {
    id: 'redsea',
    name_en: 'Red Sea',
    name_ar: 'البحر الأحمر',
    defaultZone: 'Zone 5',
    cities: [],
  },
  {
    id: 'matruh',
    name_en: 'Matruh',
    name_ar: 'مطروح',
    defaultZone: 'Zone 5',
    cities: [],
  },
  {
    id: 'northcoast',
    name_en: 'North Coast',
    name_ar: 'الساحل الشمالي',
    defaultZone: 'Zone 6',
    cities: [],
  },
  {
    id: 'southsinai',
    name_en: 'South Sinai',
    name_ar: 'جنوب سيناء',
    defaultZone: 'Zone 7',
    cities: [],
  },
  {
    id: 'newvalley',
    name_en: 'New Valley',
    name_ar: 'الوادي الجديد',
    defaultZone: 'Zone 7',
    cities: [],
  },
]
